// •	code (the employee code should be autogenerated and start with 'EMP' followed with 4 random and unique numbers)

const coder = ()=>{
    const numbers = Math.floor(1000 + Math.random() * 9000);
    return `EMP-${numbers}`
}


export default coder